<?php

/**
 * This is tour category template. The template has the following available variables:
 * 
 * - $category
 *   Category entity object
 *   
 * - $tours   
 *   An array of tour entity objects that belong to current category
 *   
 *   You can also include pagination partial to render pagination block.
 */

?>

<h2 class="page-header"><?= $category->getName(); ?></h2>

<div class="row">
    <?php foreach ($tours as $tour): ?>
    <div class="col-lg-3 col-md-4 col-xs-6">
        <a href="<?= $tour->getUrl(); ?>" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="<?= $tour->getImageUrl('400x400'); ?>" alt="<?= $tour->getName(); ?>" />
        </a>
    </div>
    <?php endforeach; ?>
</div>

<?php $this->loadPartial('bs-pagination'); ?>